terraform {
  required_version = ">= 1.5.0"

  required_providers {
    oci = {
      source  = "oracle/oci"
      version = ">= 5.0.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.25.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.12.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.0.0"
    }
  }
}

# OCI provider — credentials supplied via env vars or ~/.oci/config
provider "oci" {
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  region           = var.region
}

# Kubernetes provider — targets the OKE cluster created by Akash's module.
# Kubeconfig is generated by `oci ce cluster create-kubeconfig`.
provider "kubernetes" {
  config_path = var.kubeconfig_path
}

# Helm provider — same cluster, uses the same kubeconfig.
# Helm provider v3 changed `kubernetes {}` block to an assignment.
provider "helm" {
  kubernetes = {
    config_path = var.kubeconfig_path
  }
}
