# ============================================================
# OCI Authentication
# ============================================================

variable "tenancy_ocid" {
  description = "OCID of your OCI tenancy"
  type        = string
}

variable "user_ocid" {
  description = "OCID of the OCI user running Terraform"
  type        = string
}

variable "fingerprint" {
  description = "Fingerprint of the API signing key"
  type        = string
}

variable "private_key_path" {
  description = "Local path to the OCI API private key (.pem)"
  type        = string
  default     = "~/.oci/oci_api_key.pem"
}

variable "region" {
  description = "OCI region (e.g. us-ashburn-1)"
  type        = string
  default     = "us-ashburn-1"
}

# ============================================================
# Cluster Access
# ============================================================

variable "kubeconfig_path" {
  description = "Path to the kubeconfig for the OKE cluster (generated by Akash's module)"
  type        = string
  default     = "~/.kube/config"
}

# ============================================================
# Kubeflow Platform
# ============================================================

variable "kf_version" {
  description = "Kubeflow manifests Git branch or tag to install"
  type        = string
  default     = "master"
}

variable "kf_components" {
  description = "List of Kubeflow component paths (relative to manifests repo) to install via kustomize"
  type        = list(string)
  default = [
    "common/cert-manager/cert-manager/base",
    "common/istio-1-22/istio-crds/base",
    "common/istio-1-22/istio-namespace/base",
    "common/istio-1-22/istio-install/overlays/oauth2-proxy",
    "common/oauth2-proxy/overlays/m2m-dex-and-kind",
    "common/dex/overlays/oauth2-proxy",
    "common/knative/knative-serving/overlays/gateways",
    "contrib/kserve/kserve",
    "contrib/kserve/models-web-app/overlays/kubeflow",
    "apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user",
    "apps/centraldashboard/overlays/oauth2-proxy",
    "common/kubeflow-namespace/base",
    "common/kubeflow-roles/base",
    "common/istio-1-22/kubeflow-istio-resources/base",
    "apps/profiles/upstream/overlays/kubeflow",
  ]
}

# ============================================================
# Milvus
# ============================================================

variable "milvus_namespace" {
  description = "Kubernetes namespace for docs-agent components (Milvus, RBAC, API server)"
  type        = string
  default     = "docs-agent"
}

variable "milvus_release_name" {
  description = "Helm release name for Milvus standalone"
  type        = string
  default     = "my-release"
}

variable "milvus_chart_version" {
  description = "Milvus Helm chart version to deploy"
  type        = string
  default     = "4.2.7" # Pin a known-good version; update deliberately
}

# ============================================================
# LLM — External API (default, no GPU required)
# ============================================================

variable "external_llm_endpoint" {
  description = "OpenAI-compatible chat completions endpoint when deploy_kserve = false"
  type        = string
  default     = "https://api.groq.com/openai/v1/chat/completions"
}

variable "external_llm_model" {
  description = "Model name passed to the external LLM endpoint"
  type        = string
  default     = "llama-3.1-8b-instant"
}

variable "external_llm_api_key" {
  description = "API key for the external LLM provider (Groq, Together.ai, etc.)"
  type        = string
  sensitive   = true
  default     = ""
}

# ============================================================
# LLM — KServe (optional, requires GPU node)
# ============================================================

variable "deploy_kserve" {
  description = "Set to true to deploy a KServe InferenceService (requires a GPU node pool)"
  type        = bool
  default     = false
}

variable "huggingface_token" {
  description = "HuggingFace token for downloading gated models (required when deploy_kserve = true)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "kserve_model_id" {
  description = "HuggingFace model ID to serve via KServe"
  type        = string
  default     = "RedHatAI/Llama-3.1-8B-Instruct"
}

# ============================================================
# API Server
# ============================================================

variable "api_image" {
  description = "Docker image for the docs-agent API server (FastAPI)"
  type        = string
  # No default — must be supplied. Build and push the image first.
}

variable "api_replicas" {
  description = "Number of API server pod replicas"
  type        = number
  default     = 1
}
