# ============================================================
# OCI Authentication
# ============================================================

variable "compartment_id" {
  description = "OCI compartment OCID to deploy all resources into"
  type        = string
}

variable "cluster_name" {
  description = "Display name for the OKE cluster and VCN resources"
  type        = string
  default     = "docs-agent-cluster"
}

variable "k8s_version" {
  description = "Kubernetes version for the OKE cluster (e.g. v1.30.1)"
  type        = string
  default     = "v1.30.1"
}

variable "node_count" {
  description = "Number of ARM worker nodes (2 for HA on free tier)"
  type        = number
  default     = 2
}

variable "node_ocpus" {
  description = "OCPUs per node — free tier allows 4 total across A1.Flex"
  type        = number
  default     = 2
}

variable "node_memory_gb" {
  description = "Memory per node in GB — free tier allows 24 GB total"
  type        = number
  default     = 12
}

variable "node_boot_volume_gb" {
  description = "Boot volume size per node in GB"
  type        = number
  default     = 50
}

variable "tenancy_ocid" {
  description = "OCID of your OCI tenancy"
  type        = string
}

variable "user_ocid" {
  description = "OCID of the OCI user running Terraform"
  type        = string
}

variable "fingerprint" {
  description = "Fingerprint of the API signing key"
  type        = string
}

variable "private_key_path" {
  description = "Local path to the OCI API private key (.pem)"
  type        = string
  default     = "~/.oci/oci_api_key.pem"
}

variable "region" {
  description = "OCI region (e.g. us-ashburn-1)"
  type        = string
  default     = "us-ashburn-1"
}

# ============================================================
# Cluster Access
# ============================================================

variable "kubeconfig_path" {
  description = "Path to the kubeconfig for the OKE cluster (generated by Akash's module)"
  type        = string
  default     = "~/.kube/config"
}

# ============================================================
# Kubeflow Platform
# ============================================================

variable "kf_version" {
  description = "Kubeflow manifests Git branch or tag to install"
  type        = string
  default     = "master"
}

variable "kf_components" {
  description = "List of Kubeflow component paths (relative to manifests repo) to install via kustomize"
  type        = list(string)
  default = [
    "common/cert-manager/cert-manager/base",
    "common/istio-1-22/istio-crds/base",
    "common/istio-1-22/istio-namespace/base",
    "common/istio-1-22/istio-install/overlays/oauth2-proxy",
    "common/oauth2-proxy/overlays/m2m-dex-and-kind",
    "common/dex/overlays/oauth2-proxy",
    "common/knative/knative-serving/overlays/gateways",
    "contrib/kserve/kserve",
    "contrib/kserve/models-web-app/overlays/kubeflow",
    "apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user",
    "apps/centraldashboard/overlays/oauth2-proxy",
    "common/kubeflow-namespace/base",
    "common/kubeflow-roles/base",
    "common/istio-1-22/kubeflow-istio-resources/base",
    "apps/profiles/upstream/overlays/kubeflow",
  ]
}

# ============================================================
# Milvus
# ============================================================

variable "milvus_namespace" {
  description = "Kubernetes namespace for docs-agent components (Milvus, RBAC, API server)"
  type        = string
  default     = "docs-agent"
}

variable "milvus_release_name" {
  description = "Helm release name for Milvus standalone"
  type        = string
  default     = "my-release"
}

variable "milvus_chart_version" {
  description = "Milvus Helm chart version to deploy"
  type        = string
  default     = "4.2.7" # Pin a known-good version; update deliberately
}

# ============================================================
# LLM — Groq (used by kagent ModelConfig)
# ============================================================

variable "groq_api_key" {
  description = "Groq API key for the kagent ModelConfig"
  type        = string
  sensitive   = true
}

variable "llm_model" {
  description = "Groq model name passed to the kagent ModelConfig"
  type        = string
  default     = "llama-3.1-8b-instant"
}

variable "llm_base_url" {
  description = "OpenAI-compatible base URL for the LLM provider"
  type        = string
  default     = "https://api.groq.com/openai/v1"
}

# ============================================================
# LLM — KServe (optional, requires GPU node)
# ============================================================

variable "deploy_kserve" {
  description = "Set to true to deploy a KServe InferenceService (requires a GPU node pool)"
  type        = bool
  default     = false
}

variable "huggingface_token" {
  description = "HuggingFace token for downloading gated models (required when deploy_kserve = true)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "kserve_model_id" {
  description = "HuggingFace model ID to serve via KServe"
  type        = string
  default     = "RedHatAI/Llama-3.1-8B-Instruct"
}

# ============================================================
# MCP Server
# ============================================================

variable "mcp_image" {
  description = "Docker image for the MCP server (kagent-feast-mcp/mcp-server/). Built by Santosh."
  type        = string
  # No default — Santosh is building and publishing this image.
}

variable "mcp_replicas" {
  description = "Number of MCP server pod replicas"
  type        = number
  default     = 1
}

variable "milvus_password" {
  description = "Milvus root password (default Milvus standalone install uses 'Milvus')"
  type        = string
  sensitive   = true
  default     = "Milvus"
}

# ============================================================
# Istio
# ============================================================

variable "istio_enabled" {
  description = "Set to true on OCI cluster (Istio installed). Deploys Milvus AuthorizationPolicies. Set false for local Docker Desktop testing."
  type        = bool
  default     = true
}
